VI:
  empirical_prior: true
  learn_global_variances: false
  min_concentration: 0.001
  num_particles: 25
  num_posterior_samples: 2500
  num_prior_samples: 1000
data:
  data_dimension: 5
  dataset: SYNTHETIC
  init_method: Leiden
  neighborhood_agg: mean
  neighborhood_size: 1
  num_clusters: 7
  num_pcs: 3
  resolution: 0.47
flows:
  batch_size: 512
  flow_length: 8
  gconv_type: SGCN
  hidden_layers:
  - 128
  - 128
  - 128
  lr: 0.001
  num_epochs: 1000
  patience: 25
  posterior_flow_type: MAF
  prior_flow_type: CNF
