VI:
  empirical_prior: true
  learn_global_variances: false
  min_concentration: 0.001
  num_particles: 3
  num_posterior_samples: 2500
  num_prior_samples: 1000
data:
  data_dimension: 5
  dataset: SYNTHETIC
  init_method: Louvain
  neighborhood_agg: mean
  neighborhood_size: 2
  num_clusters: 7
  num_pcs: 3
  resolution: 0.65
flows:
  batch_size: 512
  flow_length: 2
  gconv_type: SAGE
  hidden_layers:
  - 512
  - 512
  - 512
  - 512
  lr: 0.001
  num_epochs: 1000
  patience: 50
  posterior_flow_type: MAF
  prior_flow_type: CNF
