#!/bin/bash
export CUDA_VISIBLE_DEVICES=5

python nf_graphs.py --config_name=1
python nf_graphs.py --config_name=4
python nf_graphs.py --config_name=7
python nf_graphs.py --config_name=10
python nf_graphs.py --config_name=13
python nf_graphs.py --config_name=16
python nf_graphs.py --config_name=19
python nf_graphs.py --config_name=22
python nf_graphs.py --config_name=25
python nf_graphs.py --config_name=28
python nf_graphs.py --config_name=31
python nf_graphs.py --config_name=34
python nf_graphs.py --config_name=37
python nf_graphs.py --config_name=40
python nf_graphs.py --config_name=43
python nf_graphs.py --config_name=46
python nf_graphs.py --config_name=49
python nf_graphs.py --config_name=52
python nf_graphs.py --config_name=55
python nf_graphs.py --config_name=58
python nf_graphs.py --config_name=61
python nf_graphs.py --config_name=64
python nf_graphs.py --config_name=67
python nf_graphs.py --config_name=70
python nf_graphs.py --config_name=73
python nf_graphs.py --config_name=76
python nf_graphs.py --config_name=79
python nf_graphs.py --config_name=82
