data:
  dataset: "DLPFC"
  data_dimension: 10
  num_clusters: 7
  resolution: 0.45
  num_pcs: 10
  init_method: "K-Means"
  neighborhood_size: 1
  neighborhood_agg: "mean"
VI:
  empirical_prior: True
  learn_global_variances: False
  min_concentration: 0.001
  num_prior_samples: 100
  num_posterior_samples: 1
  num_particles: 10
flows:
  flow_type: "CNF"
  flow_length: 32
  hidden_layers: [512, 512, 512, 512]
  num_epochs: 1
  batch_size: 512
  patience: 25
  lr: 0.001
