data:
  dataset: "SYNTHETIC"
  data_dimension: 5
  num_clusters: 7
  resolution: 0.65 # 0.47 for Leiden, 0.65 for Louvain when K = 7
  num_pcs: 3
  init_method: "mclust"
  neighborhood_size: 1
  neighborhood_agg: "mean"
VI:
  empirical_prior: True
  learn_global_variances: False
  min_concentration: 0.001
  num_prior_samples: 100
  num_posterior_samples: 2500
  num_particles: 25
  gamma: 1.5
flows:
  flow_type: "CNF"
  flow_length: 32
  hidden_layers: [512, 512]
  num_epochs: 1
  batch_size: 512
  patience: 25
  lr: 0.001
