data:
  dataset: "SYNTHETIC"
  data_dimension: 5
  num_clusters: 7
  resolution: 0.45
  num_pcs: 3
  init_method: "K-Means"
  neighborhood_size: 1
  neighborhood_agg: "mean"
VI:
  empirical_prior: True
  learn_global_variances: False
  min_concentration: 0.1
  num_prior_samples: 100
  num_posterior_samples: 100
  num_particles: 10
  gamma: 1.5
flows:
  flow_type: "GF"
  flow_length: 2
  hidden_layers: [128, 128, 128]
  num_epochs: 1000
  batch_size: 256
  patience: 5
  lr: 0.0001
