data:
  dataset: "SYNTHETIC"
  data_dimension: 5
  num_clusters: 7
  resolution: 0.47
  num_pcs: 5
  init_method: "Leiden"
  neighborhood_size: 3
  neighborhood_agg: "mean"
VI:
  empirical_prior: True
  learn_global_variances: False
  min_concentration: 0.001
  num_prior_samples: 100
  num_posterior_samples: 2500
  num_particles: 10
flows:
  flow_type: "CNF"
  flow_length: 32
  hidden_layers: [512, 512, 512]
  num_epochs: 1000
  batch_size: 512
  patience: 25
  lr: 0.001
