VI:
  empirical_prior: true
  learn_global_variances: false
  min_concentration: 0.001
  num_particles: 3
  num_posterior_samples: 2500
  num_prior_samples: 1000
data:
  data_dimension: 8
  dataset: DLPFC
  init_method: K-Means
  neighborhood_agg: mean
  neighborhood_size: 1
  num_clusters: 7
  num_pcs: 8
  resolution: 0.25
flows:
  batch_size: -1
  gconv_type: SAGE
  hidden_layers:
  - 128
  - 128
  lr: 0.001
  num_epochs: 10000
  patience: 50
  posterior_flow_length: 16
  posterior_flow_type: NSF
  prior_flow_length: 2
  prior_flow_type: MAF
